[package]
name = "athena"
version = "0.1.0"
edition = "2021"
authors = ["Duyet <me@duyet.net>"]

[dependencies]
anyhow = { version = "1.0.68", features = ["backtrace"] }
aws-config = "0.53.0"
aws-sdk-athena = "0.23.0"
bat = "0.22.1"
chrono = "0.4.23"
clap = { version = "4.1.1", features = ["derive"] }
devtimer = "4.0.1"
env_logger = "0.10.0"
log = "0.4.17"
regex = "1.7.1"
tera = "1.17.1"
tokio = { version = "1.24.2", features = ["full"] }
walkdir = "2.3.2"

[dev-dependencies]
assert_cmd = "2.0.8"
indoc = "2.0.0"
predicates = "2.1.5"
serial_test = "1.0.0"
tempfile = "3.3.0"
