[package]
name = "athena"
version = "0.1.0"
edition = "2021"
authors = ["Duyet <me@duyet.net>"]

[dependencies]
anyhow = { version = "1.0.60", features = ["backtrace"] }
aws-config = "0.47.0"
aws-sdk-athena = "0.17.0"
bat = "0.21.0"
chrono = "0.4.21"
clap = { version = "3.2.16", features = ["derive"] }
devtimer = "4.0.1"
env_logger = "0.9.0"
log = "0.4.17"
regex = "1.6.0"
tera = "1.16.0"
tokio = { version = "1.20.1", features = ["full"] }
walkdir = "2.3.2"

[dev-dependencies]
assert_cmd = "2.0.4"
indoc = "1.0.7"
predicates = "2.1.1"
serial_test = "0.8.0"
tempfile = "3.3.0"
