[package]
name = "athena"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.60", features = ["backtrace"] }
clap = { version = "3.2.16", features = ["derive"] }
log = "0.4.17"
tera = "1.16.0"

[dev-dependencies]
assert_cmd = "2.0.4"
indoc = "1.0.7"
predicates = "2.1.1"
tempfile = "3.3.0"
